FROM ubuntu:20.04
COPY . /app
RUN mkdir /workspace
RUN apt update \
    && apt install -y python3.8 \
    && apt install -y python3-pip \
    && pip3 install redis==3.5.3 \
    && pip3 install flask==1.1.2 \
    && pip3 install flask-cors==3.0.10 \
    && pip3 install flask-sqlalchemy==2.4.4 \
    && pip3 install pymysql==1.0.2 \
    && apt install -y vim \
    && apt install -y iputils-ping \
    && apt install -y lsof \
    && apt install -y telnet \
    && apt install -y curl 
CMD ["/app/run.sh"]


